# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qyx18/Documents/system3/XPart/XPart/XPart.srcs/sources_1/ip/Rom/Rom.xci
# IP: The module: 'Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qyx18/Documents/system3/XPart/XPart/XPart.srcs/sources_1/ip/Rom/Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/qyx18/Documents/system3/XPart/XPart/XPart.srcs/sources_1/ip/Rom/Rom.xci
# IP: The module: 'Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qyx18/Documents/system3/XPart/XPart/XPart.srcs/sources_1/ip/Rom/Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
